### ISSUE TITLE
Road to 1.0.0

### ISSUE THREAD

**Issue by clsource** [NinjasCL/domepunk#1]
This library is beta until the following components are ready.
The `Since:1.0.0` in docs is there only to be ready when the lib is done.

- [ ] PubSub Event System
- [x] Logging System
- [x] State Machines
- [ ] Entity - Actor System
- [ ] Hitboxes
- [x] Ogmo Parser
- [x] Simple Science Helpers (Math, Probabilities)
- [ ] Sample Games
- [ ] Animation Helpers (Easing, Tweens)
- [ ] Common Components (Cursor, Typewritter)
- [ ] Documentation
- [x] Tests
- [ ] Anything else?

**Comment by clsource** [comment]
Hello @purefox48, sorry for contacting you using Github issues.
I stumbled upon your code snippets for Wren at https://rosettacode.org/wiki/Category:Wren

I am requesting permission to use some of those in this project. Since the rosetta license is not clear about the code license. Would be possible to make them available under a compatible license?.

Thanks 👍

**Comment by PureFox48** [comment]
Hi there and thanks for getting in touch.

If you haven't see it already [this page](http://rosettacode.org/wiki/Rosetta_Code:Copyrights) covers the RC copyright position. Thankfully, the last paragraph enables me to license my contributions under terms more permissive than the GNU FDL.

Accordingly I'm pleased to make my contributions available to you under the [MIT License](https://opensource.org/licenses/MIT) which, of course, is the same license to which Wren and DOME themselves are subject. I will update my RC user page shortly.

I'm sorry that I haven't found the time to provide separate documentation for the various modules. You have to read through the source to find out what methods are available and what they do. At least though there are usually plenty of examples of usage on RC.

Also there's no versioning. If I discover a bug, I generally fix it straightaway and add new features from time to time. However, I try to ensure any changes are backwards compatible so that I don't have to change examples that have already been written.

**Comment by clsource** [comment]
Thanks for your kindness @PureFox48 
I have made a backup of the available modules here:
[rosetta-wren.zip](https://github.com/NinjasCL/domepunk/files/5579060/rosetta-wren.zip)

It would be easier to link a repository that you own to credit your work.
Otherwise, I can create a repo for these files to be available and make the proper attributions there too.

Which way is more comfortable for you?.

Thanks again for your awesome work 👍

**Comment by PureFox48** [comment]
As you have a lot more experience of using github than I have, I  think I'd be more comfortable (and it would certainly be quicker!) if you created the repository yourself. I can then concentrate on the RC side of things and writing some more modules. Complex numbers is the next one on my list and I'd also like to do something on trees (AVL, red and black etc.).

Incidentally, I share your admiration for DOME which is simply awesome. Although I'm not a games programmer as such, there are quite a lot of tasks on RC which require the use of 2D graphics - drawing fancy curves, image manipulation etc. - and DOME has given me a tool to tackle those.

**Comment by clsource** [comment]
Ok the repo would be https://github.com/NinjasCL-labs/wren-rosetta 👍
